"""add user authentication columns

Revision ID: 228370e69681
Revises: 6cec9f05f2a6
Create Date: 2026-08-20 16:49:25.420166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '228370e69681'
down_revision: Union[str, Sequence[str], None] = '6cec9f05f2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('password_hash', sa.String(length=200), nullable=True))
    # server_default so the column can be added to a table that already has
    # rows; existing seeded users stay active.
    op.add_column('app_user', sa.Column('is_active', sa.Boolean(),
                                        nullable=False, server_default=sa.true()))
    op.add_column('app_user', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'last_login_at')
    op.drop_column('app_user', 'is_active')
    op.drop_column('app_user', 'password_hash')
    # ### end Alembic commands ###
