"""initial schema

Revision ID: 6cec9f05f2a6
Revises: 
Create Date: 2026-08-20 15:10:22.297847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cec9f05f2a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype', native_enum=False, length=32), nullable=False),
    sa.Column('default_tax_code', sa.String(length=10), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'HIGH', name='risklevel', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('uen', sa.String(length=20), nullable=True),
    sa.Column('profile', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uen')
    )
    op.create_table('merchant_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('match_pattern', sa.String(length=200), nullable=False),
    sa.Column('match_type', sa.Enum('CONTAINS', 'PREFIX', name='matchtype', native_enum=False, length=32), nullable=False),
    sa.Column('account_id', sa.String(length=10), nullable=False),
    sa.Column('tax_code', sa.String(length=10), nullable=True),
    sa.Column('confirm_count', sa.Integer(), nullable=False),
    sa.Column('created_from_correction_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('last_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.code'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['created_from_correction_id'], ['correction.id'], name='fk_rule_from_correction', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'match_pattern', name='uq_rule_client_pattern')
    )
    op.create_index('ix_rule_client_active', 'merchant_rule', ['client_id', 'is_active'], unique=False)
    op.create_table('run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('started_by', sa.Integer(), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'AWAITING_EXTRACTION_REVIEW', 'AWAITING_REVIEW', 'COMPLETED', 'FAILED', name='runstatus', native_enum=False, length=32), nullable=False),
    sa.Column('langgraph_thread_id', sa.String(length=64), nullable=True),
    sa.Column('model_used', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_calls', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['started_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_client_id'), 'run', ['client_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('UNKNOWN', 'BANK_STATEMENT', 'INVOICE', 'RECEIPT', 'PAYROLL', 'OTHER', name='documenttype', native_enum=False, length=32), nullable=False),
    sa.Column('original_filename', sa.String(length=400), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('field_legibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('account_holder', sa.String(length=200), nullable=True),
    sa.Column('reconciles', sa.Boolean(), nullable=True),
    sa.Column('vendor_name', sa.String(length=200), nullable=True),
    sa.Column('doc_number', sa.String(length=64), nullable=True),
    sa.Column('doc_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'file_hash', name='uq_document_hash')
    )
    op.create_index(op.f('ix_document_client_id'), 'document', ['client_id'], unique=False)
    op.create_index('ix_document_client_type', 'document', ['client_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_document_run_id'), 'document', ['run_id'], unique=False)
    op.create_table('bank_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('raw_description', sa.Text(), nullable=False),
    sa.Column('bank_reference', sa.String(length=64), nullable=True),
    sa.Column('money_in', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('money_out', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('field_legibility', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_txn_client_date', 'bank_transaction', ['client_id', 'txn_date'], unique=False)
    op.create_index('ix_txn_document_line', 'bank_transaction', ['document_id', 'line_no'], unique=False)
    op.create_table('allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('account_id', sa.String(length=10), nullable=True),
    sa.Column('tax_code', sa.String(length=10), nullable=True),
    sa.Column('decision_method', sa.Enum('RULE', 'LLM', 'HUMAN', name='decisionmethod', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('AUTO_POSTED', 'NEEDS_REVIEW', 'CLIENT_QUERY', 'APPROVED', name='allocationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('matched_document_id', sa.Integer(), nullable=True),
    sa.Column('matched_rule_id', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision_method <> 'HUMAN' OR confidence IS NULL", name='ck_human_has_no_confidence'),
    sa.CheckConstraint("status <> 'APPROVED' OR account_id IS NOT NULL", name='ck_approved_needs_account'),
    sa.ForeignKeyConstraint(['account_id'], ['account.code'], ),
    sa.ForeignKeyConstraint(['approved_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transaction.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['matched_rule_id'], ['merchant_rule.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alloc_run_status', 'allocation', ['run_id', 'status'], unique=False)
    op.create_index(op.f('ix_allocation_bank_transaction_id'), 'allocation', ['bank_transaction_id'], unique=False)
    op.create_table('correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=True),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('corrected_by', sa.Integer(), nullable=False),
    sa.Column('correction_type', sa.Enum('EXTRACTION', 'CATEGORISATION', name='correctiontype', native_enum=False, length=32), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('from_account_id', sa.String(length=10), nullable=True),
    sa.Column('to_account_id', sa.String(length=10), nullable=True),
    sa.Column('from_tax_code', sa.String(length=10), nullable=True),
    sa.Column('to_tax_code', sa.String(length=10), nullable=True),
    sa.Column('from_confidence', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('create_rule', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transaction.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['corrected_by'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correction_allocation_id'), 'correction', ['allocation_id'], unique=False)
    # A cycle: allocation -> merchant_rule -> correction -> allocation. This
    # edge is added last, once both tables exist. Autogenerate does not emit
    # use_alter foreign keys, so it is written out here.
    op.create_foreign_key(
        "fk_rule_from_correction",
        "merchant_rule", "correction",
        ["created_from_correction_id"], ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("fk_rule_from_correction", "merchant_rule", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correction_allocation_id'), table_name='correction')
    op.drop_table('correction')
    op.drop_index(op.f('ix_allocation_bank_transaction_id'), table_name='allocation')
    op.drop_index('ix_alloc_run_status', table_name='allocation')
    op.drop_table('allocation')
    op.drop_index('ix_txn_document_line', table_name='bank_transaction')
    op.drop_index('ix_txn_client_date', table_name='bank_transaction')
    op.drop_table('bank_transaction')
    op.drop_index(op.f('ix_document_run_id'), table_name='document')
    op.drop_index('ix_document_client_type', table_name='document')
    op.drop_index(op.f('ix_document_client_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_run_client_id'), table_name='run')
    op.drop_table('run')
    op.drop_index('ix_rule_client_active', table_name='merchant_rule')
    op.drop_table('merchant_rule')
    op.drop_table('client')
    op.drop_table('app_user')
    op.drop_table('account')
    # ### end Alembic commands ###
